name: GoldenApple
version: 0.1
main: com.bendude56.goldenapple.GoldenApple
website: https://www.github.com/bendude56/GoldenApple
authors: ['ben_dude56', 'Deaboy']
softdepend: [Spout, WorldEdit]
commands:
    permissions:
        usage: Use /permissions help for help
        description: Edits group and user permissions
        aliases: ['p', 'gapermissions' ]